
services:
  
  api:
    build: . 
    
    container_name: mi_api_contactos_v2 
    ports:
      - "5000:8000" 
    volumes:
      - ./app:/app/app 
                       
                       
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: ${DATABASE_URL}    #postgresql://user:password@db:5432/mydatabase 
      JWT_SECRET_KEY: ${JWT_SECRET_KEY} 
      
    depends_on:
      - db 
    env_file:
      - ./.env # Carga las variables de entorno de tu archivo .env local
    
  
  db:    
    env_file:
      - ./.env
      
    image: postgres:14 
    container_name: postgres_db_api 
    environment:
            
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - db_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432" 


volumes:
  db_data: 