
services:
  
  api:
    build: . # Dockerfile está en el directorio actual (donde está docker-compose.yml)
    # Reemplaza 'app' con el nombre de la carpeta raíz de tu aplicación Flask si es diferente
    container_name: mi_api_contactos_v2 
    ports:
      - "5000:8000" 
    volumes:
      - ./app:/app/app 
                       
                       
    environment:
      
      FLASK_ENV: development 
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase 
      JWT_SECRET_KEY: ${JWT_SECRET_KEY} 
      
    depends_on:
      - db 
    env_file:
      - ./.env # Carga las variables de entorno de tu archivo .env local
    
  
  db:
    image: postgres:14 
    container_name: postgres_db_api 
    environment:
      
      
      POSTGRES_USER: contacts
      POSTGRES_PASSWORD: KYEpostgres301020
      POSTGRES_DB: mycontacts
    volumes:
      - db_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432" 


volumes:
  db_data: 
